spring:
  application:
    name: product-service
  datasource:
    url: ${DB_HOST:jdbc:postgresql://postgres.default.svc.cluster.local:5432/product_db}
    username: product-service
    password: product-service
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true


server:
  port: 8001

grpc:
  server:
    port: 9001

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: healthz
  endpoint:
    health:
      show-details: always
